[workspace]
resolver = "2"
members = [
	"player-color-param",
]

[workspace.dependencies]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/KojoBailey/nucc-json-lib-rs"
